Fixed spotify TypeError
discordsuperutils/discord-super-utils pull request #31
Opened 2022-01-15 19:20 UTC by Ariz-z

2022-01-15 20:02 UTC, adam757521 requested changes

2022-01-15 20:02 UTC, adam757521 commented on discordSuperUtils/music/player.py
> +        cls, requester: disnake.Member, query: str, player: dict
fix this, disnake should be discord

2022-01-15 20:02 UTC, adam757521 commented on discordSuperUtils/music/player.py
> +        try:
bad logic, remake please

2022-01-16 03:58 UTC, Ariz-z reviewed
sorry

2022-01-16 03:58 UTC, closed without merging